//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subscribers
{
    using System;
    using System.Collections.Generic;
    
    public partial class active_module
    {
        public int id_active_module { get; set; }
        public int id_module { get; set; }
        public int id_role { get; set; }
    
        public virtual Moduls Moduls { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
