//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subscribers
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_subscriber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public address_subscriber()
        {
            this.Subscriber = new HashSet<Subscriber>();
        }
    
        public string number_subscriber { get; set; }
        public string prefix_code { get; set; }
        public Nullable<int> id_raion { get; set; }
        public Nullable<int> id_city { get; set; }
        public Nullable<int> id_street { get; set; }
        public string house { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Raoins Raoins { get; set; }
        public virtual Streets Streets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscriber> Subscriber { get; set; }
    }
}
