//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subscribers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscriber()
        {
            this.Subscriber_service = new HashSet<Subscriber_service>();
        }
    
        public int id_subscriber { get; set; }
        public string number_subscriber { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string patromic { get; set; }
        public int id_gender { get; set; }
        public System.DateTime date_birthday { get; set; }
        public string number_phone { get; set; }
        public string email { get; set; }
        public string address_registration { get; set; }
        public string number_subcriber { get; set; }
        public string passport_seria { get; set; }
        public string passport_number { get; set; }
        public int id_division_code { get; set; }
        public int id_issued { get; set; }
        public System.DateTime date_issued { get; set; }
        public string number_contract { get; set; }
        public System.DateTime date_conclusion { get; set; }
        public int id_type_contract { get; set; }
        public Nullable<int> id_reason_terminate { get; set; }
        public string personal_account { get; set; }
        public Nullable<System.DateTime> date_terminate { get; set; }
        public Nullable<System.DateTime> date_rent { get; set; }
        public int id_serial_number { get; set; }
    
        public virtual address_subscriber address_subscriber { get; set; }
        public virtual Division_code Division_code { get; set; }
        public virtual FMS FMS { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Reason_terminate Reason_terminate { get; set; }
        public virtual Serial_number Serial_number { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscriber_service> Subscriber_service { get; set; }
        public virtual Type_contract Type_contract { get; set; }
    }
}
